version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  postgres_data:
